---
kind: pipeline
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test

- name: build
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
    - go get
    - go build -o output
    - chmod +x output

- name: run
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
    - docker build -t ll-go .
    - docker run -d ll-go:latest

volumes:
- name: deps
  temp: {}