---
kind: pipeline
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test

- name: build
  image: golang
  commands:
    - go get
    - go build -o output
    - chmod +x output

- name: run
  image: golang
  commands:
    - go get
    - go build -o output
    - chmod +x output
    - ./output